---
title: "RWorkSheet_Sabanal#3b"
output: pdf_document
date: "2023-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = TRUE}

#1a
Respo <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
Sex <- c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2)
FathersOccu <- c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1)
Person_At_Home <- c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6)
SiblingsatSchool <- c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2)
TypesofHouses <- c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)

HouseholdData <- data.frame("Respondents" = Respo,
                              "Sex" = Sex,
                              "Fathers Occupation" = FathersOccu,
                              "Persons at Home" = Person_At_Home,
                              "Siblings at School" = SiblingsatSchool,
                              "Types of Houses" = TypesofHouses)
HouseholdData


#1b
#the data is about a Household occupants

summary(HouseholdData)

#c

#no, its 2.95

#d

first_second <- HouseholdData[1:2,]
first_second

#e
third5and2nd4 <- HouseholdData[c(3,5),c(2,4)]
third5and2nd4

#f
types_houses <- HouseholdData[,1]
types_houses


#g

MaleFatherOccu <- HouseholdData[HouseholdData$Sex == 1 & HouseholdData$Fathers.Occupation == 1, c(2,3)]
MaleFatherOccu


#h

FemaleSiblings <- HouseholdData[HouseholdData$Sex == 2 & HouseholdData$Siblings.at.School >= 5, c(2,5) ]
FemaleSiblings




#2


Num2 = data.frame(Ints=integer(),
                      Doubles=double(),
                      Characters=character(),
                      Logicals=logical(),
                      Factors=factor(),
                      stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(Num2))

#it prints the structure of the dataframe


#3

Respondents2 <- c(1,2,3,4,5,6,7,8,9,10)
Sex2 <- c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male","Female", "Male")
FathersOcc2 <- c(1,2,3,3,1,2,2,3,1,3)
PersonatHome2<- c(5,7,3,8,6,4,4,2,11,6)
SiblingsatSch2 <- c(2,3,0,5,2,3,1,2,6,2)
TypeofHouses2 <- c("Wood", "Congrete", "Congrete", "Wood", "Semi-congrete", "Semi-congrete", "Wood", "Semi-congrete", "Semi-congrete", "Congrete")

HouseholdData2 <- data.frame("Respondetns" = Respondents2,
                               "Sex" = Sex2,
                               "Fathers Occupation" = FathersOcc2,
                               "Person at Home" = PersonatHome2,
                               "Siblings at Schoo" = SiblingsatSch2,
                               "Type of Houses" = TypeofHouses2)
HouseholdData2



write.csv(HouseholdData2, file = "HouseholdData.csv")


#3a

csvHouseholdData <- read.csv(file = "HouseholdData.csv")
csvHouseholdData


#3b


csvHouseholdDataSex <- as.integer(factor(csvHouseholdData$Sex, levels = c("Male", "Female")))
csvHouseholdDataSex



#3c


csvHouseholdDataTypeofHouses <- as.integer(factor(csvHouseholdData$Type.of.Houses, levels = c("Wood", "Congrete","Semi-congrete")))

csvHouseholdDataTypeofHouses


#3d
#its already on int type
csvHouseholdData$Fathers.Occupation
csvHouseholdDataFathersOcc <- as.integer(factor(csvHouseholdData$Fathers.Occupation, levels = c("")))
csvHouseholdDataFathersOcc

#3e

csvHouseholdDataFemaleFatherOcc <- csvHouseholdData[csvHouseholdData$Sex == "Female" & csvHouseholdData$Fathers.Occupation == 2, c(3,4)]
csvHouseholdDataFemaleFatherOcc


#3f

csvHouseholdDataSibmorethan5 <- csvHouseholdData[csvHouseholdData$Siblings.at.Schoo >= 5 , c(2,6)]
csvHouseholdDataSibmorethan5


#4
# On this day, July 14, the bulk of the other attitudes are negative. This shows that some topics or events caused a sour attitude on that specific day.

# Despite the fact that all attitudes improved on this day, July 15, negative emotion remains at its peak. This implies that something happened on that day that triggered negative sentiments.

# Negative views remain widespread on July 17 and 18, although neutral and positive feelings remain essentially stable.


# On July 20, all sentiments hit rock bottom, yet there were still more negative feelings among the others. This means that nothing happened on that particular day.

# On this day, July 21, all emotions are elevated, with the negative prevailing. This might suggest that something happened on that specific day that drove people to respond adversely.

#This evidence suggests that public opinion is influenced by outside factors and shifts throughout time.



```